before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential pkg-config libgd-perl 
  - cpanm  --installdeps --notest .
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.14"
